package cn.net.tongfang.framework.security.vo;

// Generated by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * VisitAfterBorn generated by hbm2java
 */
public class VisitAfterBorn implements java.io.Serializable {

	private String id;
	private String fileNo;
	private String inputPersonId;
	private Timestamp inputDate;
	private Timestamp visitDate;
	private BigDecimal diastolicPressure;
	private BigDecimal systolicPressure;
	private String result;
	private String resultOther;
	private String afterBornDirectOther;
	private Integer transfer;
	private String transReason;
	private String transUnit;
	private String visitDoctor;
	private Timestamp nextVisitDate;
	private BigDecimal bodyHeat;
	private String health;
	private String mind;
	private String breast;
	private String breastOther;
	private String lochia;
	private String lochiaOther;
	private String metra;
	private String metraOther;
	private String wound;
	private String woundOther;
	private String other;
	private String recordType;
	private String highRisk;
	private String highRiskRemark;
	private String execDistrictNum;
	private String highRiskSearch;
	private String item;
	private Integer parities;
	
	public VisitAfterBorn() {
	}

	public VisitAfterBorn(String fileNo, String inputPersonId,
			Timestamp inputDate) {
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
	}

	public VisitAfterBorn(String fileNo, String inputPersonId,
			Timestamp inputDate, Timestamp visitDate,
			BigDecimal diastolicPressure, BigDecimal systolicPressure,
			String result, String resultOther, String afterBornDirectOther,
			Integer transfer, String transReason, String transUnit,
			String visitDoctor, Timestamp nextVisitDate, BigDecimal bodyHeat,
			String health, String mind, String breast, String breastOther,
			String lochia, String lochiaOther, String metra, String metraOther,
			String wound, String woundOther, String other, String recordType,
			String highRisk,String highRiskRemark,String execDistrictNum,
			String highRiskSearch,String item,Integer parities) {
		this.fileNo = fileNo;
		this.inputPersonId = inputPersonId;
		this.inputDate = inputDate;
		this.visitDate = visitDate;
		this.diastolicPressure = diastolicPressure;
		this.systolicPressure = systolicPressure;
		this.result = result;
		this.resultOther = resultOther;
		this.afterBornDirectOther = afterBornDirectOther;
		this.transfer = transfer;
		this.transReason = transReason;
		this.transUnit = transUnit;
		this.visitDoctor = visitDoctor;
		this.nextVisitDate = nextVisitDate;
		this.bodyHeat = bodyHeat;
		this.health = health;
		this.mind = mind;
		this.breast = breast;
		this.breastOther = breastOther;
		this.lochia = lochia;
		this.lochiaOther = lochiaOther;
		this.metra = metra;
		this.metraOther = metraOther;
		this.wound = wound;
		this.woundOther = woundOther;
		this.other = other;
		this.recordType = recordType;
		this.highRisk = highRisk;
		this.highRiskRemark = highRiskRemark;
		this.execDistrictNum = execDistrictNum;
		this.highRiskSearch = highRiskSearch;
		this.item = item;
		this.parities = parities;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getFileNo() {
		return this.fileNo;
	}

	public void setFileNo(String fileNo) {
		this.fileNo = fileNo;
	}

	public String getInputPersonId() {
		return this.inputPersonId;
	}

	public void setInputPersonId(String inputPersonId) {
		this.inputPersonId = inputPersonId;
	}

	public Timestamp getInputDate() {
		return this.inputDate;
	}

	public void setInputDate(Timestamp inputDate) {
		this.inputDate = inputDate;
	}

	public Timestamp getVisitDate() {
		return this.visitDate;
	}

	public void setVisitDate(Timestamp visitDate) {
		this.visitDate = visitDate;
	}

	public BigDecimal getDiastolicPressure() {
		return this.diastolicPressure;
	}

	public void setDiastolicPressure(BigDecimal diastolicPressure) {
		this.diastolicPressure = diastolicPressure;
	}

	public BigDecimal getSystolicPressure() {
		return this.systolicPressure;
	}

	public void setSystolicPressure(BigDecimal systolicPressure) {
		this.systolicPressure = systolicPressure;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	public String getResultOther() {
		return this.resultOther;
	}

	public void setResultOther(String resultOther) {
		this.resultOther = resultOther;
	}

	public String getAfterBornDirectOther() {
		return this.afterBornDirectOther;
	}

	public void setAfterBornDirectOther(String afterBornDirectOther) {
		this.afterBornDirectOther = afterBornDirectOther;
	}

	public Integer getTransfer() {
		return this.transfer;
	}

	public void setTransfer(Integer transfer) {
		this.transfer = transfer;
	}

	public String getTransReason() {
		return this.transReason;
	}

	public void setTransReason(String transReason) {
		this.transReason = transReason;
	}

	public String getTransUnit() {
		return this.transUnit;
	}

	public void setTransUnit(String transUnit) {
		this.transUnit = transUnit;
	}

	public String getVisitDoctor() {
		return this.visitDoctor;
	}

	public void setVisitDoctor(String visitDoctor) {
		this.visitDoctor = visitDoctor;
	}

	public Timestamp getNextVisitDate() {
		return this.nextVisitDate;
	}

	public void setNextVisitDate(Timestamp nextVisitDate) {
		this.nextVisitDate = nextVisitDate;
	}

	public BigDecimal getBodyHeat() {
		return this.bodyHeat;
	}

	public void setBodyHeat(BigDecimal bodyHeat) {
		this.bodyHeat = bodyHeat;
	}

	public String getHealth() {
		return this.health;
	}

	public void setHealth(String health) {
		this.health = health;
	}

	public String getMind() {
		return this.mind;
	}

	public void setMind(String mind) {
		this.mind = mind;
	}

	public String getBreast() {
		return this.breast;
	}

	public void setBreast(String breast) {
		this.breast = breast;
	}

	public String getBreastOther() {
		return this.breastOther;
	}

	public void setBreastOther(String breastOther) {
		this.breastOther = breastOther;
	}

	public String getLochia() {
		return this.lochia;
	}

	public void setLochia(String lochia) {
		this.lochia = lochia;
	}

	public String getLochiaOther() {
		return this.lochiaOther;
	}

	public void setLochiaOther(String lochiaOther) {
		this.lochiaOther = lochiaOther;
	}

	public String getMetra() {
		return this.metra;
	}

	public void setMetra(String metra) {
		this.metra = metra;
	}

	public String getMetraOther() {
		return this.metraOther;
	}

	public void setMetraOther(String metraOther) {
		this.metraOther = metraOther;
	}

	public String getWound() {
		return this.wound;
	}

	public void setWound(String wound) {
		this.wound = wound;
	}

	public String getWoundOther() {
		return this.woundOther;
	}

	public void setWoundOther(String woundOther) {
		this.woundOther = woundOther;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getRecordType() {
		return this.recordType;
	}

	public void setRecordType(String recordType) {
		this.recordType = recordType;
	}

	public String getHighRisk() {
		return highRisk;
	}

	public void setHighRisk(String highRisk) {
		this.highRisk = highRisk;
	}

	public String getHighRiskRemark() {
		return highRiskRemark;
	}

	public void setHighRiskRemark(String highRiskRemark) {
		this.highRiskRemark = highRiskRemark;
	}

	public String getExecDistrictNum() {
		return execDistrictNum;
	}

	public void setExecDistrictNum(String execDistrictNum) {
		this.execDistrictNum = execDistrictNum;
	}

	public String getHighRiskSearch() {
		return highRiskSearch;
	}

	public void setHighRiskSearch(String highRiskSearch) {
		this.highRiskSearch = highRiskSearch;
	}

	public String getItem() {
		return item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public Integer getParities() {
		return parities;
	}

	public void setParities(Integer parities) {
		this.parities = parities;
	}
	
}
